//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErofeevSession2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialCountHistory = new HashSet<MaterialCountHistory>();
            this.MaterialSupplier = new HashSet<MaterialSupplier>();
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int CountInPack { get; set; }
        public string Unit { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public double MinCount { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public int MaterialTypeID { get; set; }
        public string Image { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual ICollection<MaterialCountHistory> MaterialCountHistory { get; set; }
        public virtual ICollection<MaterialSupplier> MaterialSupplier { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
