//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErofeevSession2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErofeevUser14Entities : DbContext
    {
        public ErofeevUser14Entities()
            : base("name=ErofeevUser14Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agent { get; set; }
        public DbSet<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public DbSet<AgentType> AgentType { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialCountHistory> MaterialCountHistory { get; set; }
        public DbSet<MaterialSupplier> MaterialSupplier { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCostHistory> ProductCostHistory { get; set; }
        public DbSet<ProductMaterial> ProductMaterial { get; set; }
        public DbSet<ProductSale> ProductSale { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<Shop> Shop { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
